## Numpy
- 수학적 계산을 도와주는 녀석
- pandas의 core는 numpy다.

In [2]:
import numpy as np


In [3]:
# 1차원

arr1= np.array([1,2,3])
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
print(arr1)

<class 'numpy.ndarray'>
1
(3,)
[1 2 3]


In [4]:
#2차원

arr2= np.array([['1',2,3],[4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.dtype) # u: 문자열 21(String)
print(arr2.shape)


[['1' '2' '3']
 ['4' '5' '6']]
2
<U21
(2, 3)


In [5]:
test=['1','2.5','3.5']
test1=['1','2','3']
arr = np.array(test)
arr1=np.array(test1)
print(arr.dtype)
arr=arr.astype('float64') #astype로 형변환 가능 
print(arr.dtype)
print(arr1.dtype)


<U3
float64
<U1


In [6]:
#ndarray range 통해서 생성
arr=np.arange(10)
arr[4]
arr[0:4]
arr[arr>5]#arr>5: index값을 가져와서 데이터로 변형을 해줌 

array([6, 7, 8, 9])

In [7]:
print(np.ones((10,10),dtype =np.int64))
print('*'* 30)
print(np.ones((10,10),dtype='int64'))

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
******************************
[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [8]:
#reshape -> 차원과 크기 변경

arr = np.arange(10)

arr.reshape(2,5)
arr.reshape(5,2)
arr.reshape(-1,5)
arr.reshape(5,-1)
arr.reshape(3,4)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [9]:
#indexing
arr = np.arange(1,10) #9개
arr
arr=arr.reshape(3,3)
print(arr)
print(arr[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


In [11]:
#boolean indexing

arr = np.arange(1,10)
arr[(arr>5)| (arr==1)]

array([1, 6, 7, 8, 9])

In [13]:
#sort
arr = np.array([10,30,5,20,80])
np.sort(arr)
np.sort(arr)[::-1] #문자는 맨 앞글자의 유니코드 값을 기준으로 정렬한다.

array([80, 30, 20, 10,  5])

In [18]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

In [22]:
np.mean(arr1,axis=0) #axis=0 열, axis =1 행

array([2., 3.])

In [26]:
# Q7. 1차원 배열에서 중앙값(median)을 계산하는 코드를 작성하세요.
arr = np.array([1, 2, 3, 4, 5])
np.median(arr)

3.0

In [27]:
# Q13. 1차원 배열에서 중복되는 값을 제거하는 코드를 작성하세요.
arr = np.array([1, 2, 3, 2, 4, 3, 5])
np.unique(arr)

array([1, 2, 3, 4, 5])

### 2.pandas - Basics

In [29]:
import pandas as pd

In [34]:
#series - 1d차원
data =['A','B','C','D','E']
series = pd.Series(data)
type(series) # Series를 df에 합치는 것과 ,df와 df를 합치는 건 다른 방법으로 해야함.

series.index
series.values
series[0:3] 

series.name = 'Alphabet' #이름 지어줄 수 있음. 
series.index.name = 'No'
series

No
0    A
1    B
2    C
3    D
4    E
Name: Alphabet, dtype: object

In [35]:
#DataFrame = > 2개 이상의 컬럼으로 구성된 데이터 

data = {
    'country' : ['kor', 'usa', 'china', 'japan'],
    'rank' : [1,2,3,4],
    'grade' : ["A", "B", "C", "D"]
}

df = pd.DataFrame(data)
df

country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C
3   japan     4     D

In [39]:
#선택,추가,생성,삭제
#데이터 셀랙션 -> 데이터를 가져오는 방법 
#(1)df.컬럼명, df['컬럼명']

print(df.country) # 이 방식은 2개 이상의 컬럼을 가져올 수 없음

needs_col =['country','rank']
df_first = df[needs_col]

#display 여러개의 데이터 프레임을 동시에 보고 싶을 때 사용 
display(df_first = df[needs_col])

0      kor
1      usa
2    china
3    japan
Name: country, dtype: object


In [42]:
# (2) df.loc[인덱스값,컬럼명]
display(df)
df.loc[0:3,['country','rank']] # series 형태 

country  rank grade
0     kor     1     A
1     usa     2     B
2   china     3     C
3   japan     4     D

country  rank
0     kor     1
1     usa     2
2   china     3
3   japan     4

In [47]:
df.loc[df['rank']>=2,'grade'] #boolean indexing 

1    B
2    C
3    D
Name: grade, dtype: object

In [53]:
#(3) df.iloc[인덱스값, 컬럼의 인덱스값] => location base(항상 숫자가 들어와야합니다.)

print(df.iloc[0:3,0:1])
print(df.iloc[0:3,0:2])

  country
0     kor
1     usa
2   china
  country  rank
0     kor     1
1     usa     2
2   china     3


In [55]:
print(df.loc[1,'rank'])
df.iloc[1,1]

2


2

In [56]:
df_new = df.set_index('country')
df_new.index

Index(['kor', 'usa', 'china', 'japan'], dtype='object', name='country')

In [57]:
df.filter(like='a')

rank grade
0     1     A
1     2     B
2     3     C
3     4     D

In [58]:
#데이터 추가
president=['yoon','biden','china','japan'] #미국의 경제성장률 :4.9%
df['president']=president
df

country  rank grade president
0     kor     1     A      yoon
1     usa     2     B     biden
2   china     3     C     china
3   japan     4     D     japan

In [59]:
df['gdp']=[100,2000,3000,4000]
df

country  rank grade president   gdp
0     kor     1     A      yoon   100
1     usa     2     B     biden  2000
2   china     3     C     china  3000
3   japan     4     D     japan  4000

In [62]:
df['etc']=np.nan
df

country  rank grade president   gdp  etc
0     kor     1     A      yoon   100  NaN
1     usa     2     B     biden  2000  NaN
2   china     3     C     china  3000  NaN
3   japan     4     D     japan  4000  NaN

In [63]:
df['new_rank']=df['rank']<=3
df

country  rank grade president   gdp  etc  new_rank
0     kor     1     A      yoon   100  NaN      True
1     usa     2     B     biden  2000  NaN      True
2   china     3     C     china  3000  NaN      True
3   japan     4     D     japan  4000  NaN     False

In [65]:
df.loc[4]=['singapole',5,'E','Tharman',5000,np.nan,False]
df

country  rank grade president   gdp  etc  new_rank
0        kor     1     A      yoon   100  NaN      True
1        usa     2     B     biden  2000  NaN      True
2      china     3     C     china  3000  NaN      True
3      japan     4     D     japan  4000  NaN     False
4  singapole     5     E   Tharman  5000  NaN     False

In [71]:
#삭제 -> drop()  new_rank를 지워보자
#df.drop(['new_rank'],axis=1) # 1번방법
df.drop(columns=['new_rank'],inplace=True) #2번방법
df

country  rank grade president   gdp  etc
0        kor     1     A      yoon   100  NaN
1        usa     2     B     biden  2000  NaN
2      china     3     C     china  3000  NaN
3      japan     4     D     japan  4000  NaN
4  singapole     5     E   Tharman  5000  NaN

In [72]:
df

country  rank grade president   gdp  etc
0        kor     1     A      yoon   100  NaN
1        usa     2     B     biden  2000  NaN
2      china     3     C     china  3000  NaN
3      japan     4     D     japan  4000  NaN
4  singapole     5     E   Tharman  5000  NaN

In [75]:
# NaN 데이터 처리(NaN: Not a number)
# null 데이터 처리 2가지 방식
#(1) 제거한다
#(2) 특정값으로 치환한다. 

#null 데이터 확인 -> isna(), isnull()
df.isna()
df.isna().sum()

country      0
rank         0
grade        0
president    0
gdp          0
etc          5
dtype: int64

In [79]:
#null 데이터 채우기  => fillna()
#df.fillna() # 전체 데이터에서 널 데이터 채우기 
df['etc'].fillna('앙') #특정 컬럼에서 널 데이터 채우기

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: etc, dtype: float64

In [82]:
df.loc[1,'etc']='pass'
df

country  rank grade president   gdp   etc
0        kor     1     A      yoon   100   NaN
1        usa     2     B     biden  2000  pass
2      china     3     C     china  3000   NaN
3      japan     4     D     japan  4000   NaN
4  singapole     5     E   Tharman  5000   NaN

In [84]:
df.dropna(how='any',axis=0) # naan인 행 데이터 제거 


country  rank grade president   gdp   etc
1     usa     2     B     biden  2000  pass

In [85]:
df.dropna(how='any',axis=1) # naan인 열 데이터 제거 


country  rank grade president   gdp
0        kor     1     A      yoon   100
1        usa     2     B     biden  2000
2      china     3     C     china  3000
3      japan     4     D     japan  4000
4  singapole     5     E   Tharman  5000

## 와인데이터 
- 피터 드러커: 측정할 수 없으면 관리할 ㅅ ㅜ없고, 관리할 수 없음녀 개선할 수 없다.

In [79]:
import pandas as pd
import numpy as np
pd.options.display.max_rows = 10

In [7]:
url='/Users/myeongjinlee/Downloads/winequality.csv'
pd.read_csv(url)

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
...         ...      ...      ...  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [8]:
#우리 가게 와인의 타입 별 종류는??
pd.train=pd.read_csv(url)
pd.train

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
...         ...      ...      ...  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

### 연습문제 1: 와인 데이터셋을 불러와 데이터프레임으로 만들어보세요.

### 연습문제 2: 기술통계 정보를 출력해보세요.

### 연습문제 3: 와인의 종류(quality)별로 데이터가 몇 개씩 있는지 출력해보세요.

### 연습문제 7: 각 와인의 타입(type)별로 평균 알코올 도수(alcohol)와 평균 당도(residual sugar)를 구해보세요.

### 연습문제 8: 'quality' 열의 값이 5 이상인 데이터만 추출하시오.

### 연습문제 9: 'fixed acidity' 열과 'pH' 열의 값이 각각 3 이상, 4이상 인 데이터만 추출하여 데이터 프레임을 생성하시오.

### 연습문제 10: 'volatile acidity' 열의 값이 0.5 이하인 데이터의 'quality' 열의 평균을 계산하세요.

### 연습문제 11: 'residual sugar' 열의 값이 2 이하인 데이터의 'density' 열의 중앙값을 계산하세요.

### 연습문제 12: 'alcohol' 열이 가장 높은 5개 데이터의 'quality' 열 값을 출력하세요.

### 연습문제 13: 'chlorides' 열의 값이 가장 높은 데이터 10개의 'pH' 열 값을 출력하세요.

### 연습문제 14: 'sulphates' 열의 값이 0.4 이하인 데이터의 'quality' 열 값을 1로 변경하세요.

### 연습문제 15: 'fixed acidity' 열의 값이 7 이하인 데이터의 'quality' 열 값을 0으로, 8 이상인 데이터의 'quality' 열 값을 2로 변경하세요. 나머지 데이터는 변경하지 않습니다.

### 연습문제 16: 'quality' 열의 값이 0인 데이터 중 'fixed acidity' 열의 값을 7로 변경하세요.

### 연습문제 17: 'quality' 열의 값이 6 이하인 데이터 중 'pH' 열의 값을 3으로 변경하세요.

In [41]:
df=pd.DataFrame(pd.read_csv(url))
df

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6493    red            5.9             0.550         0.10             2.2   
6494    red            6.3             0.510         0.13             2.3   
6495    red            5.9             0.645         0.12             2.0   
6496    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
...         ...      ...      ...  
6493        NaN     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

In [42]:
df.describe() #2번 문제 

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000   
mean        7.216579          0.339691     0.318722        5.444326   
std         1.296750          0.164649     0.145265        4.758125   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6495.000000          6497.000000           6497.000000  6497.000000   
mean      0.056042            30.525319            115.744574     0.994697   
std       0.035036            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6488.000000  6493.000000  6497.000000  6497.000000  
mean      3.218395     0.531215    10.491801     5.818378  
std       0.160748     0.148814     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [44]:
df.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [45]:
df['quality']

0       6
1       6
2       6
3       6
       ..
6493    6
6494    6
6495    5
6496    6
Name: quality, Length: 6497, dtype: int64

In [46]:
df['quality'].value_counts() #연습문제 3: 와인의 종류(quality)별로 데이터가 몇 개씩 있는지 출력해보세요.
df['quality'].value_counts().sort_index(ascending=True)
df.groupby('quality').mean()

fixed acidity  volatile acidity  citric acid  residual sugar  \
quality                                                                 
3             7.853333          0.517000     0.281000        5.140000   
4             7.288889          0.457963     0.272315        4.153704   
5             7.329348          0.389768     0.307721        5.804116   
6             7.178037          0.313731     0.323786        5.551182   
7             7.128962          0.288895     0.334764        4.733952   
8             6.838542          0.291010     0.332539        5.382902   
9             7.420000          0.298000     0.386000        4.120000   

         chlorides  free sulfur dioxide  total sulfur dioxide   density  \
quality                                                                   
3         0.077033            39.216667            122.033333  0.995744   
4         0.060158            20.636574            103.432870  0.994833   
5         0.064666            30.237371            120.839102  0.995849   
6         0.054168            31.165021            115.410790  0.994558   
7         0.045272            30.422150            108.498610  0.993126   
8         0.041124            34.533679            117.518135  0.992514   
9         0.027400            33.400000            116.000000  0.991460   

               pH  sulphates    alcohol  
quality                                  
3        3.257667   0.506333  10.215000  
4        3.231620   0.504884  10.180093  
5        3.212042   0.526416   9.837783  
6        3.217701   0.532466  10.587553  
7        3.227790   0.547025  11.386006  
8        3.223212   0.512487  11.678756  
9        3.308000   0.466000  12.180000

In [47]:
# 연습문제 7: 각 와인의 타입(type)별로 평균 알코올 도수(alcohol)와 평균 당도(residual sugar)를 구해보세요.
df[df['type']=='red'][['alcohol','residual sugar']].mean()

alcohol           10.422983
residual sugar     2.538806
dtype: float64

In [48]:
df[df['type']=='white'][['alcohol','residual sugar']].mean()

alcohol           10.514267
residual sugar     6.393250
dtype: float64

In [52]:
df.groupby('type').mean()


fixed acidity  volatile acidity  citric acid  residual sugar  \
type                                                                  
red         8.322104          0.527738     0.271145        2.538806   
white       6.855532          0.278252     0.334250        6.393250   

       chlorides  free sulfur dioxide  total sulfur dioxide   density  \
type                                                                    
red     0.087467            15.874922             46.467792  0.996747   
white   0.045778            35.308085            138.360657  0.994027   

             pH  sulphates    alcohol   quality  
type                                             
red    3.310864   0.658078  10.422983  5.636023  
white  3.188203   0.489835  10.514267  5.877909

In [53]:
df.groupby('type')[['alcohol','residual sugar']].mean()

alcohol  residual sugar
type                            
red    10.422983        2.538806
white  10.514267        6.393250

In [57]:
# 연습문제 8: 'quality' 열의 값이 5 이상인 데이터만 추출하시오.
df_high_quality = df[df['quality']>=5]
df_high_quality.to_csv("df_high_quality.csv",index=False)

In [60]:
df_high_quality= pd.read_csv("df_high_quality.csv")
df_high_quality

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     white            7.0             0.270         0.36            20.7   
1     white            6.3             0.300         0.34             1.6   
2     white            8.1             0.280         0.40             6.9   
3     white            7.2             0.230         0.32             8.5   
...     ...            ...               ...          ...             ...   
6247    red            5.9             0.550         0.10             2.2   
6248    red            6.3             0.510         0.13             2.3   
6249    red            5.9             0.645         0.12             2.0   
6250    red            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6247      0.062                 39.0                  51.0  0.99512  3.52   
6248      0.076                 29.0                  40.0  0.99574  3.42   
6249      0.075                 32.0                  44.0  0.99547  3.57   
6250      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
...         ...      ...      ...  
6247        NaN     11.2        6  
6248       0.75     11.0        6  
6249       0.71     10.2        5  
6250       0.66     11.0        6  

[6251 rows x 13 columns]

In [62]:
#연습문제 9: 'fixed acidity' 열과 'pH' 열의 값이 각각 3 이상, 4이상 인 데이터만 추출하여 데이터 프레임을 생성하시오.

df[(df['fixed acidity']>=3)&(df['pH']>=4)]

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
6214  red            5.4              0.74          0.0             1.2   
6219  red            5.0              0.74          0.0             1.2   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
6214      0.041                 16.0                  46.0  0.99258  4.01   
6219      0.041                 16.0                  46.0  0.99258  4.01   

      sulphates  alcohol  quality  
6214       0.59     12.5        6  
6219       0.59     12.5        6

In [65]:
#연습문제 10: 'volatile acidity' 열의 값이 0.5 이하인 데이터의 'quality' 열의 평균을 계산하세요.
df[df['volatile acidity']<=0.5]['quality'].mean()
#관심있는 산업군, 분야 ==> 기술이 있어도 그 분야에 대한 관심이 있으면 더 파괴력을 가질 수 있다. 

5.897160538769567

In [68]:
# 연습문제 11: 'residual sugar' 열의 값이 2 이하인 데이터의 'density' 열의 중앙값을 계산하세요.
df[df['residual sugar']<=2]['density'].median()

0.9928

In [82]:
# 연습문제 12: 'alcohol' 열이 가장 높은 5개 데이터의 'quality' 열 값을 출력하세요.

df.sort_values(by='alcohol', ascending=False)[['type','alcohol','quality']].head()
#df.nlargest(5, 'alcohol')['quality']


type  alcohol  quality
5550    red    14.90        5
3918  white    14.20        7
4503  white    14.05        7
3150  white    14.00        6
5040    red    14.00        6

In [84]:
#연습문제 13: 'chlorides' 열의 값이 가장 높은 데이터 10개의 'pH' 열 값을 출력하세요.
df.sort_values(by='chlorides',ascending=False)[['type','chlorides','pH']].head(10)
#print(df.sort_values(by='chlorides',ascending=False).head(10)['pH'])

type  chlorides    pH
5156  red      0.611  3.06
5049  red      0.610  2.74
5004  red      0.467  3.08
4979  red      0.464  3.13
5590  red      0.422  3.03
6268  red      0.415  3.00
6270  red      0.415  3.00
5652  red      0.415  3.09
6217  red      0.414  2.90
5949  red      0.414  3.03

In [87]:
#연습문제 14: 'sulphates' 열의 값이 0.4 이하인 데이터의 'quality' 열 값을 1로 변경하세요.
df_sulphates=df[df['sulphates']<=0.4]
df_sulphates['quality']=1
df_sulphates

<ipython-input-87-2d57405ffc5c>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_sulphates['quality']=1


type  fixed acidity  volatile acidity  citric acid  residual sugar  \
3     white            7.2             0.230         0.32             8.5   
4     white            7.2             0.230         0.32             8.5   
16    white            6.3             0.480         0.04             1.1   
17    white            NaN             0.660         0.48             1.2   
20    white            6.2             0.660         0.48             1.2   
...     ...            ...               ...          ...             ...   
6185    red            8.0             0.600         0.08             2.6   
6197    red            7.6             1.580         0.00             2.1   
6245    red            7.2             0.655         0.03             1.8   
6246    red            7.2             0.655         0.03             1.8   
6267    red            6.6             0.610         0.00             1.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
16        0.046                 30.0                  99.0  0.99280  3.24   
17        0.029                 29.0                  75.0  0.98920  3.33   
20        0.029                 29.0                  75.0  0.98920  3.33   
...         ...                  ...                   ...      ...   ...   
6185      0.056                  3.0                   7.0  0.99286  3.22   
6197      0.137                  5.0                   9.0  0.99476  3.50   
6245      0.078                  7.0                  12.0  0.99587  3.34   
6246      0.078                  7.0                  12.0  0.99587  3.34   
6267      0.069                  4.0                   8.0  0.99396  3.33   

      sulphates  alcohol  quality  
3          0.40      9.9        1  
4          0.40      9.9        1  
16         0.36      9.6        1  
17         0.39     12.8        1  
20         0.39     12.8        1  
...         ...      ...      ...  
6185       0.37     13.0        1  
6197       0.40     10.9        1  
6245       0.39      9.5        1  
6246       0.39      9.5        1  
6267       0.37     10.4        1  

[1195 rows x 13 columns]

In [89]:
# 연습문제 15: 'fixed acidity' 열의 값이 7 이하인 데이터의 'quality' 열 값을 0으로, 8 이상인 데이터의 'quality' 열 값을 2로 변경하세요. 나머지 데이터는 변경하지 않습니다.
df[df['fixed acidity']<=7]['quality']
df.loc[df['fixed acidity']<=7,'quality']=0
df.loc[df['fixed acidity']<=8,'quality']=2


In [91]:
# 연습문제 16: 'quality' 열의 값이 0인 데이터 중 'fixed acidity' 열의 값을 7로 변경하세요.
df.loc[df['fixed acidity']==0,'fixed acidity']=7
df['quality'].value_counts()

2    5352
6     470
5     431
7     165
4      51
8      16
3      11
9       1
Name: quality, dtype: int64

In [90]:
# 연습문제 17: 'quality' 열의 값이 6 이하인 데이터 중 'pH' 열의 값을 3으로 변경하세요.

df.loc[df['quality']<=6,'pH']=3

## NBA 데이터 

- 여러분은 팀에서 선수 영입을 담당는 에이전트입니다.
- 어떤 팀에서 누구를 데려오면 좋을까요? 올해 영입 전략은 어떻게 짜면 좋을까요?
- 등등

In [96]:
df= pd.read_csv('/Users/myeongjinlee/Downloads/nba.csv')
df

Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0   
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0   
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0   
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
..             ...             ...     ...      ...   ...    ...     ...   
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0   
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0   
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0   
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0   
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  
457                NaN        NaN  

[458 rows x 9 columns]

In [100]:
# 현재 각 팀별 선수는 몇 명씩 있나요?
#df.groupby('Team').size().sort_values(ascending=False)
df['Team'].value_counts().to_frame()


Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Washington Wizards        15
...                      ...
Charlotte Hornets         15
Oklahoma City Thunder     15
Los Angeles Lakers        15
Orlando Magic             14
Minnesota Timberwolves    14

[30 rows x 1 columns]

In [101]:
# 포지션별 평균 연봉은 어떻게 되나요?
df.groupby('Position')['Salary'].mean().sort_values()


Position
SG    4.009861e+06
PF    4.562483e+06
SF    4.857393e+06
PG    5.077829e+06
C     5.967052e+06
Name: Salary, dtype: float64

In [102]:
# 팀별 평균 연봉은 어떻게 되나요?
df.groupby('Team')['Salary'].mean().sort_values()



Team
Philadelphia 76ers        2.213778e+06
Portland Trail Blazers    3.220121e+06
Brooklyn Nets             3.501898e+06
Boston Celtics            4.181505e+06
Utah Jazz                 4.204006e+06
                              ...     
Golden State Warriors     5.924600e+06
Oklahoma City Thunder     6.251020e+06
Los Angeles Clippers      6.323643e+06
Miami Heat                6.347359e+06
Cleveland Cavaliers       7.642049e+06
Name: Salary, Length: 30, dtype: float64

In [119]:
# 학교별로 출신 선수가 몇 명 인지를 보고자 하면 어떻게 하면 될까요?
df.groupby('College').size().sort_values(ascending =False).to_frame().head(10) #groupby는 value_counts 불가 
#df['College'].value_counts().head(10)


0
College           
Kentucky        22
Duke            20
Kansas          18
North Carolina  16
UCLA            15
Arizona         13
Florida         10
Texas            9
Syracuse         8
Connecticut      7

In [117]:
# 연봉이 가장 많은 학교 top 10
df.groupby('College')['Salary'].mean().sort_values(ascending =False).to_frame().head(10)

Salary
College                       
Oklahoma          1.890773e+07
Louisiana Tech    1.867166e+07
San Diego State   1.640750e+07
Marquette         1.198129e+07
Texas A&M         1.177876e+07
Memphis           1.145366e+07
Davidson          1.137079e+07
Morehead State    1.123596e+07
Washington State  1.100050e+07
Georgia Tech      1.067691e+07